import type { Component, Page, Project } from '../../server/types/schema'
import type { GeneratedTask } from './tasks'

/**
 * Full AGENTS.md generation (docs/08 §8.3) — the primary instruction
 * document for handoff agents. Replaces the codegen stub with overview
 * counts, architecture tree, design-system values, routes, ordered tasks,
 * per-type component specs, testing requirements, and sync rules.
 */

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' ? (value as Record<string, unknown>) : {}
}

function str(value: unknown, fallback = ''): string {
  return typeof value === 'string' && value ? value : fallback
}

function tokenPath(tokens: Record<string, unknown>, path: string): string {
  let current: unknown = tokens
  for (const segment of path.split('.')) {
    if (current && typeof current === 'object' && segment in (current as object)) {
      current = (current as Record<string, unknown>)[segment]
    } else {
      return ''
    }
  }
  return typeof current === 'string' || typeof current === 'number' ? String(current) : ''
}

export interface AgentsMdInput {
  project: Project
  files: Array<{ path: string }>
  tasks: GeneratedTask[]
}

const COMPONENT_SPECS: Record<string, { location: string; props: string; a11y: string }> = {
  Button: {
    location: 'src/components/ui.tsx (Button)',
    props: 'variant (primary|secondary|outline|ghost|link), size (sm|md|lg), disabled, icon, onClick',
    a11y: 'role="button" via native button, keyboard accessible (Enter/Space)',
  },
  Input: {
    location: 'src/components/ui.tsx (Input)',
    props: 'type, placeholder, required, value, onChange, label, onSubmit',
    a11y: 'role="textbox" with associated label element',
  },
  Card: {
    location: 'src/components/ui.tsx (Card)',
    props: 'header, content, footer, elevation (0-3), children, onClick',
    a11y: 'section landmark when a header is present',
  },
  Navbar: {
    location: 'src/components/ui.tsx (Navbar)',
    props: 'logo, links ({label, href}[]), sticky, transparent',
    a11y: 'nav landmark with link list',
  },
  Chart: {
    location: 'src/components/ui.tsx (Chart)',
    props: 'type (line|bar|pie|doughnut|area), data ({labels, datasets}), responsive',
    a11y: 'canvas with aria-label from surrounding context',
  },
  Table: {
    location: 'src/components/ui.tsx (Table)',
    props: 'columns ({key, label}[]), data, sortable, filterable',
    a11y: 'table with th scope, sortable headers are buttons',
  },
}

export function generateAgentsMd({ project, files, tasks }: AgentsMdInput): string {
  const record = asRecord(project)
  const name = str(record.name, 'Omix App')
  const pages = (Array.isArray(record.pages) ? record.pages : []) as Page[]
  const tokens = asRecord(record.designTokens)
  const tree = files
    .map((f) => f.path)
    .sort()
    .map((p) => `- ${p}`)
    .join('\n')

  const pageComponents = (page: Page): Component[] => {
    const list = asRecord(page).components
    return Array.isArray(list) ? (list as Component[]) : []
  }
  const componentCount = pages.reduce((n, p) => n + pageComponents(p).length, 0)
  const usedTypes = [...new Set(pages.flatMap((p) => pageComponents(p).map((c) => str(asRecord(c).type, 'unknown'))))]

  const routes = pages
    .map((p) => {
      const r = asRecord(p)
      const names = pageComponents(p)
        .map((c) => str(asRecord(c).name) || str(asRecord(c).type))
        .join(', ')
      return `| ${str(r.path, '/')} | ${str(r.title, '')} | ${names} |`
    })
    .join('\n')

  const tasksMd = tasks
    .map(
      (t) =>
        `### ${t.id}: ${t.title}\n**Priority:** ${t.priority}\n**Dependencies:** ${t.dependencies.length > 0 ? t.dependencies.join(', ') : 'none'}\n${t.description}\n` +
        t.acceptanceCriteria.map((c) => `- [ ] ${c.description}`).join('\n')
    )
    .join('\n\n')

  const specs = usedTypes
    .map((type) => {
      const spec = COMPONENT_SPECS[type] ?? {
        location: 'src/components/ui.tsx',
        props: 'see component props in page files',
        a11y: 'follow ARIA practices for this component kind',
      }
      return `### ${type}\n**Location:** ${spec.location}\n**Props:** ${spec.props}\n**Accessibility:** ${spec.a11y}`
    })
    .join('\n\n')

  return `# Project: ${name}

> Generated by forge@omix agent handoff. Implement the tasks below in order;
> keep every quality gate green.

## Overview

- **Framework:** React + Vite
- **Styling:** Tailwind CSS (tokens in \`src/index.css\`)
- **Routing:** react-router-dom
- **Charts:** chart.js + react-chartjs-2
- **Total Pages:** ${pages.length}
- **Total Components:** ${componentCount}
- **Total Tasks:** ${tasks.length}

## Architecture

### Directory Structure

${tree}

### Design System

- Primary color: ${tokenPath(tokens, 'colors.primary')}
- Font: ${tokenPath(tokens, 'typography.fontFamily.sans')}
- Base radius: ${tokenPath(tokens, 'radius.md')}
- Base spacing: ${tokenPath(tokens, 'spacing.md')}

### Routes

| Path | Page | Components |
|------|------|------------|
${routes}

## Tasks (Implementation Order)

${tasksMd}

## Component Specifications

${specs}

## Testing Requirements

- Framework: Vitest
- Typecheck: \`tsc --noEmit\` (strict, 0 errors)
- Build: \`vite build\` must succeed
- Every task's acceptance criteria must hold before marking it done

## Files to NEVER Modify

- \`.builder/**\` — builder metadata (schema, tasks, sync rules)
- \`package.json\` — change only via package-manager commands
- \`tailwind.config.js\` — generated from design tokens
- \`src/index.css\` — generated token variables (extend, don't rewrite)

## Sync Rules

1. Work tasks in dependency order; don't start a task whose dependencies aren't done.
2. After implementing a task, update \`.builder/tasks.json\` (set \`status\` to \`done\`).
3. After all tasks are done, run tests, typecheck, and build.
4. Commit per task: \`feat: implement [task-id]\` (e.g. \`feat: implement task_page_home\`).
`
}
