import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises'
import { createHash, randomUUID } from 'node:crypto'
import path from 'node:path'

/**
 * Media asset storage (docs/17).
 *
 * Files live on disk under MEDIA_DIR and are referenced by id. The store is
 * deliberately dumb: it validates, writes, and hands back a public URL. The
 * database row is the index; the filesystem is the payload.
 *
 * SVG is the dangerous format here — an uploaded SVG is an XML document that
 * can carry <script>, event handlers, and external references. It is
 * sanitized on the way in and served with a locked-down content type.
 */

export type MediaType = 'image' | 'gif' | 'video'

/** Formats we accept, with the media type each maps to. */
const ALLOWED: Record<string, MediaType> = {
  'image/png': 'image',
  'image/jpeg': 'image',
  'image/webp': 'image',
  'image/avif': 'image',
  'image/gif': 'gif',
  'image/svg+xml': 'image',
  'video/mp4': 'video',
  'video/webm': 'video',
}

export const MAX_UPLOAD_BYTES = 25 * 1024 * 1024

export const ACCEPTED_MIME_TYPES = Object.keys(ALLOWED)

export function mediaTypeFor(mimeType: string): MediaType | null {
  return ALLOWED[mimeType] ?? null
}

export function isSvg(mimeType: string): boolean {
  return mimeType === 'image/svg+xml'
}

function mediaDir(): string {
  return process.env.MEDIA_DIR || path.join(process.env.DATABASE_URL ? path.dirname(stripFileScheme(process.env.DATABASE_URL)) : process.cwd(), 'media')
}

function stripFileScheme(url: string): string {
  return url.replace(/^file:/, '')
}

/** Extension for a mime type, used when naming the stored file. */
function extensionFor(mimeType: string, originalName: string): string {
  const fromName = path.extname(originalName).toLowerCase()
  // Trust our own map over the client's filename.
  const map: Record<string, string> = {
    'image/png': '.png',
    'image/jpeg': '.jpg',
    'image/webp': '.webp',
    'image/avif': '.avif',
    'image/gif': '.gif',
    'image/svg+xml': '.svg',
    'video/mp4': '.mp4',
    'video/webm': '.webm',
  }
  return map[mimeType] ?? fromName ?? '.bin'
}

/**
 * Strip everything executable from an SVG.
 *
 * Removes script elements, event-handler attributes, and non-http URL forms
 * (javascript:, data:). Allows the presentation attributes that make SVG
 * useful (viewBox, fill, path data, style).
 */
export function sanitizeSvg(source: string): string {
  let out = source
  // Elements that execute or embed.
  out = out.replace(/<\s*(script|foreignObject|iframe|embed|object|handler|set|animate)\b[\s\S]*?<\s*\/\s*\1\s*>/gi, '')
  out = out.replace(/<\s*(script|foreignObject|iframe|embed|object|handler)\b[^>]*\/?>/gi, '')
  // Event handlers: on*="..."
  out = out.replace(/\son[a-z]+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi, '')
  // javascript:/vbscript:/data: URLs in href/xlink:href/src
  out = out.replace(/\s(?:xlink:)?href\s*=\s*(?:"\s*(?:javascript|vbscript|data):[^"]*"|'\s*(?:javascript|vbscript|data):[^']*')/gi, '')
  return out
}

export interface StoredMedia {
  id: string
  filename: string
  storedName: string
  mimeType: string
  mediaType: MediaType
  byteSize: number
  url: string
}

export async function storeMedia(input: {
  bytes: Uint8Array
  mimeType: string
  filename: string
}): Promise<StoredMedia> {
  const mediaType = mediaTypeFor(input.mimeType)
  if (!mediaType) throw new Error(`Unsupported media type: ${input.mimeType}`)
  if (input.bytes.byteLength === 0) throw new Error('Empty upload')
  if (input.bytes.byteLength > MAX_UPLOAD_BYTES) {
    throw new Error(`Upload exceeds ${MAX_UPLOAD_BYTES} bytes`)
  }

  const bytes = isSvg(input.mimeType)
    ? new TextEncoder().encode(sanitizeSvg(new TextDecoder().decode(input.bytes)))
    : input.bytes

  // Content-addressed name: identical uploads collapse, and the extension is
  // derived from the validated mime type rather than the client's filename.
  const digest = createHash('sha256').update(bytes).digest('hex').slice(0, 32)
  const storedName = `${digest}${extensionFor(input.mimeType, input.filename)}`

  const dir = mediaDir()
  await mkdir(dir, { recursive: true })
  await writeFile(path.join(dir, storedName), bytes)

  return {
    id: randomUUID(),
    filename: path.basename(input.filename) || storedName,
    storedName,
    mimeType: input.mimeType,
    mediaType,
    byteSize: bytes.byteLength,
    url: `/api/media/files/${storedName}`,
  }
}

export async function readMedia(storedName: string): Promise<Buffer | null> {
  // storedName is generated by us, but never trust a request parameter on a
  // path join — reject anything that is not a bare filename.
  if (!/^[a-f0-9]{32}\.[a-z0-9]+$/.test(storedName)) return null
  try {
    return await readFile(path.join(mediaDir(), storedName))
  } catch {
    return null
  }
}

export async function deleteMedia(storedName: string): Promise<void> {
  if (!/^[a-f0-9]{32}\.[a-z0-9]+$/.test(storedName)) return
  try {
    await unlink(path.join(mediaDir(), storedName))
  } catch {
    // Already gone — deleting the row is what matters.
  }
}